### ISSUE TITLE
Patch not in the AUR anymore

### ISSUE THREAD

**Issue by weisbrja** [uditkarode/libxft-bgra#6]
This patch doesn't seem to be in the AUR anymore.
Could you re-upload it or has it been abandoned?
If so, what is the alternative?
As far as I know, the patch hasn't been merged into libxft, but the issue has rather been closed 2 months ago without merging, because there were still some problems left and the main person pushing towards the merge switched to wayland and wasn't interested in fixing these problems and getting the merge done anymore (https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/1).
Help is very much appreciated.

**Comment by ghost** [comment]
> "the patch hasn't been merged into libxft"

The patch was merged on Jul 11, 2022.
https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/12

**Comment by weisbrja** [comment]
Ohh, thank you! I didn't find part 2.
